### ISSUE TITLE
sbt compilation failure

### ISSUE THREAD

**Issue by sanity** [sanity/Swarm#2]
James, would you mind taking a look at this - I'm not really familiar with sbt, but it looks like its not accepting the command line parameter that enables continuations:

Swarm  master $ sbt compile
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (9911kB/619ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.4 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    15 artifacts copied, 0 already retrieved (4096kB/134ms)
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
Getting Scala 2.8.1 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (15118kB/805ms)
[info] Building project swarm 1.0-SNAPSHOT against Scala 2.8.1
[info]    using SwarmProject with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == compile ==
[info]   Source analysis: 10 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] 'compiler-interface' not yet compiled for Scala 2.8.1.final. Compiling...
[info]   Compilation completed in 19.026 s
[error] bad option: -P:continuations:enable
[error] one error found
[info] == compile ==
[error] Error running compile: Compilation failed
[info] 
[info] Total time: 21 s, completed Apr 24, 2011 12:49:44 PM
[info] 
[info] Total session time: 27 s, completed Apr 24, 2011 12:49:44 PM
[error] Error during build.

**Comment by earldouglas** [comment]
Shot in the dark, but what version of Scala and SBT are you using?  I am using 2.8.1 and 0.7.4, and running SBT with the following command:

```
java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$@"
```

**Comment by sanity** [comment]
[info] Building project swarm 1.0-SNAPSHOT against Scala 2.8.1
[info]    using SwarmProject with sbt 0.7.4 and Scala 2.7.7

I don't really understand your build command - where is sbt-launch.jar
supposed to be?

Appreciate your help!

Ian.

On Sun, Apr 24, 2011 at 12:59 PM, JamesEarlDouglas <
reply@reply.github.com>wrote:

> Shot in the dark, but what version of Scala and SBT are you using?  I am
> using 2.8.1 and 0.7.4, and running SBT with the following command:
> 
>    java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$@"
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sanity/Swarm/issues/2#comment_1050467

## 

Ian Clarke
CEO, Uprizer Labs LLC
Email: ian@uprizer.com
Ph: +1 512 422 3588

**Comment by earldouglas** [comment]
No worries!  The command comes right from the SBT docs here: http://code.google.com/p/simple-build-tool/wiki/RunningSbt

I have a script file named "sbt" which contains the java command from above and resides in the same directory as sbt-launch.jar.  This way, I run `sbt` from the command line, which executes the script (with the command in my previous comment).

**Comment by sanity** [comment]
Ah, yes - I'd forgotten but actually I've got the exact same setup.

Ian.

On Sun, Apr 24, 2011 at 1:50 PM, JamesEarlDouglas <
reply@reply.github.com>wrote:

> No worries!  The command comes right from the SBT docs here:
> http://code.google.com/p/simple-build-tool/wiki/RunningSbt
> 
> I have a script file named "sbt" which contains the above command and
> resides in the same directory as sbt-launch.jar.  This way, I run `sbt` from
> the command line, which executes the script (with the command in my previous
> comment).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sanity/Swarm/issues/2#comment_1050566

## 

Ian Clarke
CEO, Uprizer Labs LLC
Email: ian@uprizer.com
Ph: +1 512 422 3588

**Comment by earldouglas** [comment]
Were you able to past the compilation error?
