### ISSUE TITLE
Compilation failure with Swarm client

### ISSUE THREAD

**Issue by sanity** [sanity/Swarm#3]
Not quite sure what is wrong here - its claiming that its building against Scala 2.9.0 which I assume includes the continuations stuff.  Sorry, I'm not very familiar with sbt so not really able to debug it myself :-(

[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] Building project swarm 1.0-SNAPSHOT against Scala 2.9.0
[info]    using SwarmProject with sbt 0.7.7 and Scala 2.7.7

> project swarm-twitter-node1
> Set current project to swarm-twitter-node1 1.0-SNAPSHOT
> jetty-run
> [info] 
> [info] == swarm-core / compile ==
> [info]   Source analysis: 8 new/modified, 0 indirectly invalidated, 0 removed.
> [info] Compiling main sources...
> [error] bad option: -P:continuations:enable
> [error] one error found
> [info] == swarm-core / compile ==
> [info] 
> [info] == swarm-core / copy-resources ==
> [info] == swarm-core / copy-resources ==
> [info] 
> [info] == swarm-twitter-core / copy-resources ==
> [info] == swarm-twitter-core / copy-resources ==
> [info] 
> [info] == swarm-twitter-node1 / copy-resources ==
> [info] == swarm-twitter-node1 / copy-resources ==
> [error] Error running compile: Compilation failed
> [info] 
> [info] Total time: 4 s, completed May 22, 2011 9:14:25 AM

**Comment by wrwills** [comment]
Hi,

I wasn't able to compile the twitter stuff because repo1.maven.org seems to
be down now so I could get all the updates down, but swarm-core did compile
for me.

One thought is that you need to make sure that you update your sbt-launch
jar to 0.7.7 for compiling under scala 2.9.0 to work.

-Rob

**Comment by earldouglas** [comment]
Your system might be missing the Scala 2.9.0 libraries.  Try running update from the SBT console:

> sbt
> update
> compile

**Comment by sanity** [comment]
Ah, I think that fixed it - thanks!
