### ISSUE TITLE
Build errors when I try twitter-demo

### ISSUE THREAD

**Issue by sanity** [sanity/Swarm#5]
Just did a pull, last commit is:

commit 4fe3d028a17e60d237a61909db148fb9a518ec9a
Author: James Earl Douglas james@earldouglas.com
Date:   Mon May 30 10:23:11 2011 -0700

```
extract RefMap into its own class file
```

I then try the Twitter demo, but get the following errors:

$ sbt

> twitter-demo
> [info] 
> [info] == twitter-demo ==
> [info]   Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
> [info] Compiling main sources...
> [error] /Users/ian/workspace/Swarm/swarm-twitter/node1/src/main/scala/swarm/twitter/SwarmTwitter.scala:3: not found: type SwarmTwitterTemplate
> [error] class SwarmTwitter extends SwarmTwitterTemplate("node1", 9998, 9997)
> [error]                            ^
> [error] /Users/ian/workspace/Swarm/swarm-twitter/node1/src/main/scala/swarm/twitter/SwarmTwitter.scala:3: too many arguments for constructor Object: ()java.lang.Object
> [error] class SwarmTwitter extends SwarmTwitterTemplate("node1", 9998, 9997)
> [error]                    ^
> [error] two errors found
> [info]   Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
> [info] Compiling main sources...
> [error] /Users/ian/workspace/Swarm/swarm-twitter/node2/src/main/scala/swarm/twitter/SwarmTwitter.scala:3: not found: type SwarmTwitterTemplate
> [error] class SwarmTwitter extends SwarmTwitterTemplate("node2", 9997, 9998)
> [error]                            ^
> [error] /Users/ian/workspace/Swarm/swarm-twitter/node2/src/main/scala/swarm/twitter/SwarmTwitter.scala:3: too many arguments for constructor Object: ()java.lang.Object
> [error] class SwarmTwitter extends SwarmTwitterTemplate("node2", 9997, 9998)
> [error]                    ^
> [error] two errors found
> [info] == twitter-demo ==
> [success] Successful.

**Comment by earldouglas** [comment]
The twitter-demo command does not have an implicit compile command built-in, though this would be very nice to have.

Try running compile first:

$ sbt

> compile
> twitter-demo

**Comment by sanity** [comment]
I'm an idiot, I assumed that running the demo would trigger recompilation.

Ian.

On Mon, May 30, 2011 at 3:11 PM, JamesEarlDouglas <
reply@reply.github.com>wrote:

> The twitter-demo command does not have an implicit compile command
> built-in, though this would be very nice to have.
> 
> Try running compile first:
> 
> $ sbt
> 
> > compile
> > twitter-demo
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sanity/Swarm/issues/5#comment_1263351

## 

Ian Clarke
CEO, Uprizer Labs LLC
Email: ian@uprizer.com
Ph: +1 512 422 3588

**Comment by earldouglas** [comment]
I updated the sbt configuration so that running `twitter-demo` automatically runs `compile` when necessary.
