### ISSUE TITLE
Data repositories are not thread-safe

### ISSUE THREAD

**Issue by earldouglas** [sanity/Swarm#9]
The Store class and its Repository implementation are thread-unsafe, which will result in trouble when multiple clients use Swarm simultaneously.  A thread-safe approach to managing per-node repositories as well as inter-node updates and relocations is needed.  Consider using STM as a model pattern.

**Comment by bitwalker** [comment]
Just pushed a336582 and cba5c35, which should fix this issue, at least naively.

**Comment by bitwalker** [comment]
Also 992ca34
